// Package dashboard renders an audit as one self-contained HTML page: a
// treemap of the hotspot ranking, sized by complexity and coloured by score.
//
// Self-contained is the whole design. There is no javascript, no web font and
// no external stylesheet, the layout is computed in Go and written out as
// static SVG, so the page renders the same from a laptop with no network as it
// does from one with a network, and it can be attached to a mail or committed
// next to the code it describes without dragging anything along.
package dashboard

import (
	"fmt"
	"html"
	"math"
	"strings"
)

// Item is one ranked file, already relative to the analysed directory and
// already slashed. The numbers are the ones `warpmap hotspots` prints.
type Item struct {
	Path       string
	Churn      int
	Complexity int
	Score      float64
}

// Page is everything the dashboard shows.
type Page struct {
	Project  string
	Version  string
	Files    int
	Edges    int
	Hotspots []Item
}

const (
	canvasW = 960.0
	canvasH = 540.0
	// tableN is how many rows the ranking under the map lists. The map itself
	// carries every file; this is the part you can read off without hovering.
	tableN = 10
	// charW is the advance of one character at the label font size, which is
	// monospace so that this is a constant rather than a guess.
	charW = 6.0
)

// Render returns the whole HTML document.
func Render(p Page) string {
	var b strings.Builder
	b.WriteString("<!doctype html>\n<html lang=\"en\">\n<head>\n")
	b.WriteString("<meta charset=\"utf-8\">\n")
	b.WriteString("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n")
	fmt.Fprintf(&b, "<title>warpmap: %s</title>\n", esc(p.Project))
	b.WriteString("<style>\n" + css + "</style>\n</head>\n<body>\n")

	fmt.Fprintf(&b, "<h1>%s</h1>\n", esc(p.Project))
	fmt.Fprintf(&b, "<p class=\"sub\">%d files, %d import edges, %d ranked</p>\n",
		p.Files, p.Edges, len(p.Hotspots))

	if len(p.Hotspots) == 0 {
		b.WriteString("<p class=\"empty\">no source files here to map. warpmap reads " +
			"TypeScript, JavaScript and Python; check the directory and the ignore globs " +
			"in warpmap.json.</p>\n")
	} else {
		writeMap(&b, p)
		writeLegend(&b)
		writeTable(&b, p)
	}

	b.WriteString("<p class=\"foot\">generated by warpmap")
	if p.Version != "" {
		fmt.Fprintf(&b, " %s", esc(p.Version))
	}
	b.WriteString("</p>\n</body>\n</html>\n")
	return b.String()
}

func writeMap(b *strings.Builder, p Page) {
	root := Tree(p.Hotspots)
	Layout(root, canvasW, canvasH)

	fmt.Fprintf(b, "<svg class=\"map\" viewBox=\"0 0 %g %g\" width=\"%g\" height=\"%g\" "+
		"preserveAspectRatio=\"xMidYMid meet\" xmlns=\"http://www.w3.org/2000/svg\" "+
		"role=\"img\" aria-label=\"hotspot treemap\">\n", canvasW, canvasH, canvasW, canvasH)
	draw(b, root)
	b.WriteString("</svg>\n")
}

// draw paints a node and then everything inside it, so a directory's frame and
// label go down before its children cover the rest of the box.
func draw(b *strings.Builder, n *Node) {
	if n.Rect.W <= 0 || n.Rect.H <= 0 {
		return
	}
	if n.Leaf() {
		fill := heat(n.Item.Score)
		fmt.Fprintf(b, "<g><rect class=\"file\" x=\"%.1f\" y=\"%.1f\" width=\"%.1f\" height=\"%.1f\" fill=\"%s\"/>",
			n.Rect.X, n.Rect.Y, n.Rect.W, n.Rect.H, fill)
		fmt.Fprintf(b, "<title>%s\nscore %.3f, churn %d, complexity %d</title>",
			esc(n.Item.Path), n.Item.Score, n.Item.Churn, n.Item.Complexity)
		if label := fit(n.Name, n.Rect.W); label != "" && n.Rect.H >= 12 {
			fmt.Fprintf(b, "<text class=\"flabel\" x=\"%.1f\" y=\"%.1f\" fill=\"%s\">%s</text>",
				n.Rect.X+4, n.Rect.Y+n.Rect.H/2+3.5, ink(fill), esc(label))
		}
		b.WriteString("</g>\n")
		return
	}
	if n.Path != "" {
		fmt.Fprintf(b, "<g><rect class=\"dir\" x=\"%.1f\" y=\"%.1f\" width=\"%.1f\" height=\"%.1f\"/>",
			n.Rect.X, n.Rect.Y, n.Rect.W, n.Rect.H)
		fmt.Fprintf(b, "<title>%s</title>", esc(n.Path))
		if label := fit(n.Name, n.Rect.W); label != "" && n.Rect.H >= headerH {
			fmt.Fprintf(b, "<text class=\"dlabel\" x=\"%.1f\" y=\"%.1f\">%s</text>",
				n.Rect.X+4, n.Rect.Y+11, esc(label))
		}
		b.WriteString("</g>\n")
	}
	for _, c := range n.Children {
		draw(b, c)
	}
}

func writeLegend(b *strings.Builder) {
	b.WriteString("<div class=\"legend\">\n")
	b.WriteString("<span>area: complexity</span>\n")
	b.WriteString("<span class=\"ramp\">score 0.000")
	for i := 0; i <= 8; i++ {
		fmt.Fprintf(b, "<i style=\"background:%s\"></i>", heat(float64(i)/8))
	}
	b.WriteString("1.000</span>\n")
	b.WriteString("<span>one box per file, nested by directory</span>\n")
	b.WriteString("</div>\n")
}

func writeTable(b *strings.Builder, p Page) {
	n := tableN
	if n > len(p.Hotspots) {
		n = len(p.Hotspots)
	}
	b.WriteString("<table>\n<thead><tr><th>#</th><th>score</th><th>churn</th>" +
		"<th>complexity</th><th>file</th></tr></thead>\n<tbody>\n")
	for i, h := range p.Hotspots[:n] {
		fmt.Fprintf(b, "<tr><td>%d</td><td>%.3f</td><td>%d</td><td>%d</td><td>%s</td></tr>\n",
			i+1, h.Score, h.Churn, h.Complexity, esc(h.Path))
	}
	b.WriteString("</tbody>\n</table>\n")
}

// --- colour ---

type rgb struct{ R, G, B float64 }

var (
	cold = rgb{238, 242, 246}
	hot  = rgb{176, 42, 28}
)

// heat maps a hotspot score to a fill colour.
//
// The ramp runs on the square root of the score rather than the score itself.
// The score is normalised churn times normalised complexity, so it is heavily
// skewed: on a real repo almost every file sits below 0.05, and a linear ramp
// paints the entire map the same near-white with one red box in it. The square
// root spreads the crowded low end without reordering anything.
func heat(score float64) string {
	t := math.Sqrt(clamp01(score))
	c := rgb{
		R: cold.R + (hot.R-cold.R)*t,
		G: cold.G + (hot.G-cold.G)*t,
		B: cold.B + (hot.B-cold.B)*t,
	}
	return fmt.Sprintf("#%02x%02x%02x", round(c.R), round(c.G), round(c.B))
}

// ink picks the label colour that stays readable on a given fill.
func ink(fill string) string {
	var r, g, b int
	if _, err := fmt.Sscanf(fill, "#%02x%02x%02x", &r, &g, &b); err != nil {
		return "#1b2733"
	}
	if (299*r+587*g+114*b)/1000 < 140 {
		return "#ffffff"
	}
	return "#1b2733"
}

func clamp01(v float64) float64 {
	if v < 0 {
		return 0
	}
	if v > 1 {
		return 1
	}
	return v
}

func round(v float64) int {
	i := int(math.Round(v))
	if i < 0 {
		return 0
	}
	if i > 255 {
		return 255
	}
	return i
}

// --- text ---

// fit shortens a label to what its box can hold, and returns "" when the box
// cannot hold enough of it to be worth reading.
func fit(name string, width float64) string {
	max := int((width - 8) / charW)
	if max < 3 {
		return ""
	}
	r := []rune(name)
	if len(r) <= max {
		return name
	}
	return string(r[:max-2]) + ".."
}

// esc escapes for both text nodes and double-quoted attributes: a file name is
// whatever the filesystem allowed, which includes angle brackets and quotes.
func esc(s string) string { return html.EscapeString(s) }

const css = `:root { color-scheme: light; }
body {
  margin: 0 auto; padding: 24px; max-width: 1008px;
  font: 14px/1.5 ui-sans-serif, system-ui, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
  color: #1b2733; background: #ffffff;
}
h1 { margin: 0; font-size: 20px; font-weight: 600; }
.sub { margin: 2px 0 18px; color: #5a6b7c; }
.empty { padding: 24px; background: #f7f9fb; border: 1px solid #dfe6ec; border-radius: 4px; }
svg.map { width: 100%; height: auto; display: block; border: 1px solid #dfe6ec; border-radius: 4px; }
rect.file { stroke: #ffffff; stroke-width: 1; }
rect.dir { fill: #f2f5f8; stroke: #c3cedb; stroke-width: 1; }
text.dlabel { font: 600 10px ui-monospace, "SF Mono", Consolas, monospace; fill: #5a6b7c; }
text.flabel { font: 10px ui-monospace, "SF Mono", Consolas, monospace; }
.legend {
  display: flex; flex-wrap: wrap; gap: 8px 24px;
  margin: 12px 0 24px; color: #5a6b7c; font-size: 12px;
}
.ramp { display: inline-flex; align-items: center; gap: 4px; }
.ramp i { width: 20px; height: 10px; display: inline-block; border: 1px solid #dfe6ec; }
table { border-collapse: collapse; width: 100%; font-size: 13px; }
th, td { text-align: left; padding: 5px 10px; border-bottom: 1px solid #eef2f6; }
th { color: #5a6b7c; font-weight: 600; }
td:nth-child(-n+4) { text-align: right; font-variant-numeric: tabular-nums; }
th:nth-child(-n+4) { text-align: right; }
td:last-child { font-family: ui-monospace, "SF Mono", Consolas, monospace; }
.foot { margin-top: 20px; color: #8a99a8; font-size: 12px; }
`
